name: punch
base: core22
summary: CLI tool for tracking, reporting, and submitting your work tasks and timecards
description: |
  Punch is a command-line tool for tracking, reporting, and submitting your work tasks and timecards.
  It supports quick task entry, interactive mode, reporting, exporting, and Salesforce Lightning timecard submission.

grade: stable
confinement: strict

icon: snap/gui/icon.svg

apps:
  punch:
    command: bin/punch
    completer: bin/punch-completer
    plugs:
      - home
      - network
      - network-bind
      - browser-support
      - x11
      - wayland
    environment:
      PLAYWRIGHT_BROWSERS_PATH: $SNAP/playwright-browsers

adopt-info: punch

parts:
  punch:
    plugin: python
    source: .
    build-packages:
      - execstack
      - python3-dev
      - python3-pip
      - python3-venv
      - gcc
      - libffi-dev
      - libssl-dev
    stage-packages:
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libdrm2
      - libgbm1
      - libgtk-3-0
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libasound2
      - libxss1
      - libxtst6
      - libappindicator3-1
      - libnspr4
      - libnss3
      - libx11-xcb1
      - libxshmfence1
      - libxcb-dri3-0
      - libxkbcommon0
      - libxrender1
      - libxext6
      - libxfixes3
      - libxinerama1
      - libxcomposite1
      - libxcursor1
      - libxi6
      - libxrandr2
      - libxss1
      - libxtst6
      - libappindicator3-1
      - libdbusmenu-glib4
      - libdbusmenu-gtk3-4
      - libsecret-1-0
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libx11-xcb1
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxrandr2
      - libgbm1
      - libasound2
      - libatk-bridge2.0-0
      - libgtk-3-0
      - libxkbcommon0
      - libxshmfence1
      - libnspr4
      - libdrm2
      - libxcb-dri3-0
      - libcups2
      - libxinerama1
      - libxcursor1
      - libxi6
      - libappindicator3-1
      - libdbusmenu-glib4
      - libdbusmenu-gtk3-4
      - libsecret-1-0
      - libnotify4
    override-pull: |
      set -euo pipefail
      craftctl default

      git fetch --tags --force >/dev/null 2>&1 || true

      if tag=$(git describe --tags --exact-match 2>/dev/null); then
        # Strip leading "v"
        version="${tag#v}"
      else
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        latest_tag="${latest_tag#v}"
        ts=$(date -u -d "@$(git log -1 --format=%ct)" +%Y%m%d%H%M%S)
        hash=$(git rev-parse --short=7 HEAD)
        version="${latest_tag}+${ts}.${hash}"
      fi

      craftctl set version="$version"
    override-build: |
      craftctl default
      export PLAYWRIGHT_BROWSERS_PATH=$SNAPCRAFT_PART_INSTALL/playwright-browsers
      playwright install --with-deps firefox
      # if [ -e $SNAPCRAFT_PART_INSTALL/playwright-browsers/firefox-1490/libonnxruntime.so ]
      execstack --clear-execstack $SNAPCRAFT_PART_INSTALL/playwright-browsers/firefox-1490/firefox/libonnxruntime.so
      # fi
      install -m755 punch-completion.bash $SNAPCRAFT_PART_INSTALL/bin/punch-completer
      install -D -m644 "$CRAFT_PART_SRC/CHANGELOG.md" \
        "$CRAFT_PART_INSTALL/usr/share/punch/CHANGELOG.md"

# Notes:
# - This snap uses Poetry for dependency management and builds the wheel.
# - The Playwright browser dependencies are included in stage-packages for headless browser support.
# - You may need to run `playwright install` after installing the snap to fetch browser binaries.
