name: Build Snap package

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Snapcraft
        uses: snapcore/action-build@v1

      - name: Build the snap
        run: snapcraft

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: punch-snap
          path: ./*.snap