name: Run Python unit tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install
          poetry run playwright install --with-deps chromium

      - name: Run unit tests
        run: |
          poetry run python -m unittest discover -s tests
